version: "3.7"

networks:
  web:
    external: true
  c4s-website:

services:

  app:
    image: ghcr.io/chaostreff-flensburg/c4s-website/frontend:latest
    restart: unless-stopped
    networks:
      - web
      - c4s-website
    labels:
      - traefik.enable=true
      - traefik.http.routers.c4s-website.rule=Host(`42.ccc.de`)
      - traefik.http.routers.c4s-website.entrypoints=websecure
      - traefik.http.routers.c4s-website.tls=true
      - traefik.http.routers.c4s-website.certresolver=le
      - traefik.http.services.c4s-website.loadbalancer.server.port=8080
      - traefik.docker.network=web
