version: "3.7"

networks:
  web:
    external: true

services:
  app:
    image: ghcr.io/chaostreff-flensburg/c4s-website/frontend:latest
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.c4s-website.rule=Host(`42.ccc.de`)"
      - "traefik.http.routers.c4s-website.entrypoints=https,http"
      - "traefik.http.services.c4s-website.loadbalancer.server.port=80"
      - "traefik.http.routers.c4s-website.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=web"
